- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: VSultanovResourceGroup
      name: sultVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: VSultanovResourceGroup
      name: sultSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: sultVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: VSultanovResourceGroup
      allocation_method: Static
      name: sultPublicIP
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: VSultanovResourceGroup
      name: sultNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
        - name: 8080
          protocol: Tcp
          destination_port_range: 8080
          access: Allow
          priority: 1002
          direction: Inbound
        - name: 8081
          protocol: Tcp
          destination_port_range: 8081
          access: Allow
          priority: 1003
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: VSultanovResourceGroup
      name: sultNIC
      virtual_network: sultVnet
      subnet: sultSubnet
      public_ip_name: sultPublicIP
      security_group: sultNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: VSultanovResourceGroup
      name: sultVM
      vm_size: Standard_DS1_v2
      admin_username: slava
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: /home/slava/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7gUlEblho4GVcej+52jSnJG1LB3x8ecrhsH01w9XxB/XijmRhCmTYXFUDix6eO2xU4ctg7D9/DJPg7TaW3B8OBiQvld7LDEXwnapkig24VzzN79rTSFLfgtYr/H1xSI5FO8PZmx9X8dsYyi4mPmryCthuiuFpG/XU1nE7N/Khidsct4oohdB1xY1XLklUdaLji+guwPh5BVmJnRHweOMe0veoN61i7JCREzcL0vqXQmzBrA5gGaehPDYitScWCvIRz6iejHr1HSNkdSh0/XP+AK8JQsNjO218mQqfmrpMJ81nEir8rACiRmn82sPjeev0KlKs3E6FAX1obpNzgXZr slava@slava-VirtualBox"
      network_interfaces: sultNIC
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest

